name: cmx_apps_backend
description: A server app using the shelf package and Docker.
version: 0.1.0

environment:
  sdk: ^3.0.6

dependencies:
  args: ^2.3.0
  crypto: ^3.0.3
  postgres: ^2.6.2
  shelf: ^1.4.0
  shelf_plus: ^1.7.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
